
services:
  wimoor-mysql:
    image: ${REMOTE_HUB}wimoor-mysql:${DB_VERSION}
    container_name: wimoor-mysql
    build:
      context: config/mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ${BASE_DIR}/wimoor/mysql:/var/lib/mysql
    #  - ./config/mysql/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - network

  wimoor-nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: wimoor-nacos
    env_file:
      - wimoor-nacos.env
    volumes:
      - ${BASE_DIR}/wimoor/nacos/logs:/home/nacos/logs
      - ./config/nacos/application.properties:/home/nacos/conf/application.properties
      - ./config/nacos/init.d:/home/nacos/init.d
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      wimoor-mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - network

  wimoor-seata:
    image: seataio/seata-server:1.4.2
    container_name: wimoor-seata
    volumes:
      - ./config/seata/registry.conf:/seata-server/resources/registry.conf
    ports:
      - "7091:7091"
      - "8091:8091"
    depends_on:
      - wimoor-nacos
      - wimoor-mysql
    networks:
      - network

  wimoor-redis:
    image: redis:7.2.4
    container_name: wimoor-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ${BASE_DIR}/wimoor/redis/data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${BASE_DIR}/wimoor/redis/logs:/logs
    #配置文件启动
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - network

  wimoor-gateway:
    image: ${REMOTE_HUB}wimoor-gateway:${GATEWAY_VERSION}
    container_name: wimoor-gateway
    environment:
      - WIMOOR_NACOS_HOST=wimoor-nacos
    command: java -Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5099 -jar /app.jar --server.port=8099
    ports:
      - 8099:8099
      - 5099:5099
    depends_on:
      - wimoor-nacos
    networks:
      - network

  wimoor-amazon:
    image: ${REMOTE_HUB}wimoor-amazon:${AMAZON_VERSION}
    container_name: wimoor-amazon
    environment:
      - WIMOOR_NACOS_HOST=wimoor-nacos
      - WIMOOR_SEATA_HOST=wimoor-seata
    ports:
      - 8093:8093
      - 5093:5093
    command: java -Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5093 -jar /app.jar --server.port=8093
    depends_on:
      - wimoor-nacos
      - wimoor-seata
      - wimoor-gateway
    networks:
      - network

  wimoor-erp:
    image: ${REMOTE_HUB}wimoor-erp:${ERP_VERSION}
    container_name: wimoor-erp
    environment:
      - WIMOOR_NACOS_HOST=wimoor-nacos
      - WIMOOR_SEATA_HOST=wimoor-seata
    ports:
      - 8086:8086
      - 5086:5086
    command: java -Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5086 -jar /app.jar --server.port=8086
    depends_on:
      - wimoor-nacos
      - wimoor-seata
      - wimoor-gateway
    networks:
      - network

  wimoor-amazon-adv:
    image: ${REMOTE_HUB}wimoor-amazon-adv:${AMAZON_ADV_VERSION}
    container_name: wimoor-amazon-adv
    environment:
      - WIMOOR_NACOS_HOST=wimoor-nacos
    ports:
      - 8092:8092
      - 5092:5092
    command: java -Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5092 -jar /app.jar --server.port=8092
    depends_on:
      - wimoor-nacos
      - wimoor-gateway
    networks:
      - network

  wimoor-auth:
    image: ${REMOTE_HUB}wimoor-auth:${AUTH_VERSION}
    container_name: wimoor-auth
    environment:
      - WIMOOR_NACOS_HOST=wimoor-nacos
    ports:
      - 8087:8087
      - 5087:5087
    command: java -Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5087 -jar /app.jar --server.port=8087
    depends_on:
      - wimoor-nacos
      - wimoor-gateway
    networks:
      - network

  wimoor-admin:
    image: ${REMOTE_HUB}wimoor-admin:${ADMIN_VERSION}
    container_name: wimoor-admin
    environment:
      - WIMOOR_NACOS_HOST=wimoor-nacos
      - WIMOOR_REDIS_HOST=wimoor-redis
      - WIMOOR_MYSQL_HOST=wimoor-mysql
    ports:
      - 8085:8085
      - 5085:5085
    command: java -Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5085 -jar /app.jar --server.port=8085
    depends_on:
      - wimoor-nacos
      - wimoor-redis
      - wimoor-gateway
    networks:
      - network

  wimoor-init:
    image: alpine:latest
    container_name: wimoor-init
    volumes:
      - ./config/init.d:/init.d
    environment:
      - NACOS_SERVICE_HOST=wimoor-nacos
      - NACOS_SERVICE_PORT=8848
    command: ["/bin/sh", "/init.d/nacos-init.sh"]
    depends_on:
      - wimoor-nacos
      - wimoor-mysql
    networks:
      - network


  wimoor-ui:
    image: ${REMOTE_HUB}wimoor-ui:${UI_VERSION}
    container_name: wimoor-ui
    build:
      context: wimoor-ui
      dockerfile: docker/Dockerfile
    volumes:
      - ./config/ui/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - network

networks:
  network:
    driver: bridge
