Remove-Item -Path "./logs/win/*" -Force

Write-Output start
Start-Process -FilePath "mvn" -ArgumentList "spring-boot:run -pl wimoor-gateway -Dspring-boot.run.jvmArguments=`"-Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5099`"" -RedirectStandardOutput "./logs/win/gateway.log" -RedirectStandardError "./logs/win/gateway_err.log" -NoNewWindow
Start-Process -FilePath "mvn" -ArgumentList "spring-boot:run -pl amazon-boot -Dspring-boot.run.jvmArguments=`"-Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5093`"" -RedirectStandardOutput "./logs/win/amazon.log" -RedirectStandardError "./logs/win/amazon_err.log" -NoNewWindow
Start-Process -FilePath "mvn" -ArgumentList "spring-boot:run -pl erp-boot -Dspring-boot.run.jvmArguments=`"-Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5086`"" -RedirectStandardOutput "./logs/win/erp.log" -RedirectStandardError "./logs/win/erp_err.log" -NoNewWindow
Start-Process -FilePath "mvn" -ArgumentList "spring-boot:run -pl amazon-adv-boot -Dspring-boot.run.jvmArguments=`"-Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5092`"" -RedirectStandardOutput "./logs/win/adv.log" -RedirectStandardError "./logs/win/adv_err.log" -NoNewWindow
Start-Process -FilePath "mvn" -ArgumentList "spring-boot:run -pl wimoor-auth -Dspring-boot.run.jvmArguments=`"-Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5087`"" -RedirectStandardOutput "./logs/win/auth.log" -RedirectStandardError "./logs/win/auth_err.log" -NoNewWindow
Start-Process -FilePath "mvn" -ArgumentList "spring-boot:run -pl admin-boot -Dspring-boot.run.jvmArguments=`"-Xdebug -Xms128m -Xmx128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5085`"" -RedirectStandardOutput "./logs/win/admin.log" -RedirectStandardError "./logs/win/admin_err.log" -NoNewWindow
Write-Output end