USE `db_amazon`;
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('CouponRedemptionFee', 'CouponRedemptionFee', '*');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Fee Adjustment', 'Item Fee Adjustment', 'FBA Pick & Pack Fee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Income Tax Charged', 'other-transaction', 'MiscAdjustment');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Lightning Deal Fee', 'LightningDealFee', 'LightningDealFee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Lightning Deal Fee', 'LightningDealFee', 'LightningDealFee Special');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Order', 'DirectPayment', 'CollectOnDeliveryRevenue');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Order', 'ShipmentFees', 'FBA transportation fee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Order_Retrocharge', 'ItemPrice', 'ShippingTax');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Order_Retrocharge', 'ItemPrice', 'Tax');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'FBA Inventory Reimbursement', 'CS_ERROR_NON_ITEMIZED');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'FBA Inventory Reimbursement', 'INCORRECT_FEES_NON_ITEMIZED');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'ItemFees', 'FBACustomerReturnPerOrderFee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'ItemFees', 'FBACustomerReturnPerUnitFee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'ItemFees', 'FBACustomerReturnWeightBasedFee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'Manual Processing Fee Reimbursement', 'Manual Processing Fee Reimbursement');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'A2ZGuaranteeRecovery');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'BuyerRecharge');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'ChargeBackRecovery');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'CommissionCorrection');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Current Reserve Amount');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'DisposalComplete');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'FBA International Freight Duties and Taxes Charge');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'FBA International Freight Shipping Charge');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'FBAInboundTransportationFee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'FBAInboundTransportationProgramFee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'HighVolumeListing');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Inventory Placement Service Fee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Inventory Storage Overage Fee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Manual Processing Fee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'MiscAdjustment');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'NonSubscriptionFeeAdj');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Paid Services Fee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Payable to Amazon');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Previous Reserve Amount Balance');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'RemovalComplete');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'RemovalCompleteCGST');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'RemovalCompleteSGST');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Shipping label purchase for return');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Storage Fee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'StorageBillingCGST');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'StorageBillingSGST');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'StorageRenewalBilling');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'StorageRenewalBillingCGST');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'StorageRenewalBillingSGST');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Subscription Fee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'SubscriptionFeeCorrection');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Successful charge');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Transfer of funds unsuccessful: A transfer could not be initiated because the transfer amount does n');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Transfer of funds unsuccessful: Amazon has cancelled your transfer of funds.');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Transfer of funds unsuccessful: An unexpected issue occurred. Please contact Seller Support for more');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Transfer of funds unsuccessful: We could not transfer funds to your bank account because the account');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'Unplanned Service Fee - Barcode label missing');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('other-transaction', 'other-transaction', 'WarehousePrep');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Refund_Retrocharge', 'ItemPrice', 'ShippingTax');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Refund_Retrocharge', 'ItemPrice', 'Tax');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('SellerReviewEnrollmentPayment', 'Review Enrollment Fee', 'Early Reviewer Program fee');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('ServiceFee', 'Cost of Advertising', 'TransactionTotalAmount');
INSERT IGNORE INTO `t_amz_settlement_amount_type_nonsku` (`transaction_type`, `amount_type`, `amount_description`) VALUES ('Tax', 'Tax Withheld', '*');
